version: "3"

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/influxdb-datasource.yaml:/etc/grafana/provisioning/datasources/influxdb-datasource.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  telegraf:
    image: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./MOCK_DATA.csv:/tmp/data.csv
  influxdb:
    image: influxdb
    ports:
      - 8089:8089
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
  pi-plotter:
    build: .
    depends_on:
      - influxdb
    volumes:
      - ./pi-plotter:/usr/src/app

volumes:
  grafana-storage:
  influxdb-storage:
