version: "3"

services:
  marax-adapter:
    build: ./containers/marax-adapter
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - marax-storage:/var/log/marax
  telegraf:
    image: telegraf
    depends_on:
      - influxdb
      - marax-adapter
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
      - marax-storage:/var/log/marax
  influxdb:
    image: influxdb
    expose:
      - 8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/influxdb-datasource.yaml:/etc/grafana/provisioning/datasources/influxdb-datasource.yaml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  pi-plotter:
    build: ./containers/pi-plotter
    depends_on:
      - influxdb
    volumes:
      - ./pi-plotter:/usr/src/app

volumes:
  grafana-storage:
  influxdb-storage:
  marax-storage:
